imports = [
    "./src/base/*",
    "./src/foretold/*",
    "./src/lesswrong/*",
    "./src/coronavirus.toml",
    "./src/locations.toml",
    "./src/movies.toml",
    "./src/orgs.toml",
]

"output" = "data.json"