imports = [
    "./data/base/*",
    "./data/foretold/*",
    "./data/lessWrong/*",
    "./data/coronavirus.toml",
    "./data/locations.toml",
    "./data/movies.toml",
    "./data/orgs.toml",
]

"output" = "data.json"