@locations/n-algeria,
@locations/n-angola,
@locations/n-benin,
@locations/n-burkina-faso,
@locations/n-burundi,
@locations/n-cameroon,
@locations/n-central-african-republic,
@locations/n-chad,
@locations/n-democratic-republic-of-the-congo,
@locations/n-republic-of-the-congo,
@locations/n-ivory-coast,
@locations/n-egypt,
@locations/n-ethiopia,
@locations/n-gabon,
@locations/n-ghana,
@locations/n-guinea,
@locations/n-kenya,
@locations/n-liberia,
@locations/n-mauritania,
@locations/n-mozambique,
@locations/n-morocco,
@locations/n-namibia,
@locations/n-niger,
@locations/n-nigeria,
@locations/n-rwanda,
@locations/n-senegal,
@locations/n-sierra-leone,
@locations/n-somalia,
@locations/n-south-africa,
@locations/n-south-sudan,
@locations/n-sudan,
@locations/n-tanzania,
@locations/n-togo,
@locations/n-tunisia,
@locations/n-uganda,
@locations/n-zambia,
@locations/n-zimbabwe,