[config]
baseId = "media"
resourceId = "movies"

  [config.aliases]
  name = "@base/properties/p-name"
  description = "@base/properties/p-description"
  instance-of = "@base/properties/p-instance-of"
  url = "@base/properties/p-url"
  movie = "@base/properties/n-movie"

[imdb-rating]
name = "IMDB Rating"

[rt-rating]
name = "Rotten Tomatoes Rating"

[box-office-wikipedia]
name = "Box Office Returns"
description = "Information gathered from wikipedia"

[metacritic]
name = "Metacritic Rating"
description = "Information gathered from wikipedia"

[captain-marvel]
name = "Captain Marvel"
url = "https://www.rottentomatoes.com/m/captain_marvel"
instance-of = "movie"

[dumbo]
name = "Dumbo"
url = "https://www.rottentomatoes.com/m/dumbo"
instance-of = "movie"

[us]
name = "Us"
url = "https://www.rottentomatoes.com/m/us"
instance-of = "movie"

[pet-semetary]
name = "Pet Semetary"
url = "https://www.rottentomatoes.com/m/us"
instance-of = "movie"

[missing-link]
name = "Missing Link"
url = "https://www.rottentomatoes.com/m/us"
instance-of = "movie"

[hellboy]
name = "Hellboy"
url = "https://www.rottentomatoes.com/m/us"
instance-of = "movie"

[avengers-endgame]
name = "Avengers: Endgame"
url = "https://www.rottentomatoes.com/m/avengers_endgame"
instance-of = "movie"

[john-wick-three]
name = "John Wick: Chapter Three"
url = "https://www.rottentomatoes.com/m/avengers_endgame"
instance-of = "movie"

[detective-pikachu]
name = "Detective Pikachu"
url = "https://www.rottentomatoes.com/m/pokemon_detective-pikachu"
instance-of = "movie"

[aladdin]
name = "Aladdin"
url = "https://www.rottentomatoes.com/m/aladdin"
instance-of = "movie"

[the-hustle]
name = "The Hustle"
url = "https://www.rottentomatoes.com/m/aladdin"
instance-of = "movie"

[rocketman]
name = "Rocketman"
url = "https://www.rottentomatoes.com/m/aladdin"
instance-of = "movie"